namespace Everestfcsweb.Enum
{
    public enum UserLoginStatus { Ok = 0, VerifyAccount = 1,ChangePassword =2,AccountClosed=3, AccountLocked =4 }
    public enum ListModelType
    {
        Vehicletype = 0,
        Roles = 1,
        Loyaltygrouping = 2,
        Stations = 3,
        Country = 4,
        Pricelist = 5,
        Discountlist = 6,
        ConsumptionType = 7,
        CardType = 8,
        Systempermission = 9,
        Paymentmodes = 10,
        SystemProduct = 11,
        SystemEquipmentMakes = 12,
        SystemCurrencies = 13,
        SystemFormulas = 14,
        SystemRewards = 15,
        SystemPhoneCodes = 16,
        Systemproductcategory = 17,
        Systemproductuom = 18,
        SystemTank=19,
        SystemCustomers = 20,
        SystemStationStaff = 21,
        SystemEquipmentModel = 22,
        SystemCardModel = 23,
        SystemAccountNumbers = 24,
        SystemAgreementAccountNumbers = 25,
        SystemCustomerAgreement=26,
        SystemAgreementAccount = 27,
        SystemLoyaltyAwardType = 28,
        SystemTenantAccounts = 29,
        SystemPump = 30,
        SystemDryProduct=31,
        SystemCreditCustomers=32,
        SystemCustomerEquipments = 33,
        SystemSuppliers = 34,
        Systemstationshifts=35,
        SystemWetProduct = 36,
        BankPaymentmodes = 37,
    }
}
